<a href="https://colab.research.google.com/github/dilshanwickramasinghe007-lab/Movie-Recommendation-System-Using-Machine-Learning/blob/main/Movie_Recommendation_System_Using_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [4]:
movies = pd.read_csv('/content/sample_data/dataset.csv')

In [5]:
movies.head()

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811

In [6]:
movies.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='object')

In [7]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10000 non-null  int64
 1   title              10000 non-null  object
 2   genre              9997 non-null   object
 3   original_language  10000 non-null  object
 4   overview           9987 non-null   object
 5   popularity         10000 non-null  float64
 6   release_date       10000 non-null  object
 7   vote_average       10000 non-null  float64
 8   vote_count         10000 non-null  int64
dtypes: float64(2), int64(2), object(5)
memory usage: 703.3+ KB

In [8]:
movies['tags'] = movies['genre'] = movies['overview']

In [9]:
movies.head()

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...,en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...,en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811,In the continuing saga of the Corleone crime f...

In [11]:
new_df = movies[['id','title','genre','overview', 'tags']]

In [12]:
new_df = new_df.drop(columns=['genre', 'overview'])

In [13]:
new_df.head()

,id,title,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
cv = CountVectorizer(max_features=10000, stop_words='english')

In [16]:
cv

CountVectorizer(max_features=10000, stop_words='english')

In [17]:
vec = cv.fit_transform(new_df['tags'].values.astype('U')).toarray()

In [18]:
vec

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [19]:
vec.shape

(10000, 10000)

In [20]:
from sklearn.metrics.pairwise import cosine_similarity

In [23]:
sin = cosine_similarity(vec)

In [24]:
sin

array([[1.        , 0.03030303, 0.02861819, ..., 0.0836242 , 0.08444007,
        0.03798686],
       [0.03030303, 1.        , 0.05723638, ..., 0.        , 0.        ,
        0.        ],
       [0.02861819, 0.05723638, 1.        , ..., 0.02632491, 0.03987261,
        0.        ],
       ...,
       [0.0836242 , 0.        , 0.02632491, ..., 1.        , 0.        ,
        0.        ],
       [0.08444007, 0.        , 0.03987261, ..., 0.        , 1.        ,
        0.        ],
       [0.03798686, 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [25]:
new_df[new_df['title'] == 'The Lego Movie'].index[0]

np.int64(1632)

In [26]:
dist = sorted(list(enumerate(sin[0])), reverse=True, key=lambda vector:vector[1])

In [27]:
dist

[(0, np.float64(1.0000000000000002)),
 (3649, np.float64(0.2321035412742638)),
 (4490, np.float64(0.20309059861498083)),
 (170, np.float64(0.20100756305184245)),
 (698, np.float64(0.20100756305184245)),
 (2991, np.float64(0.20100756305184245)),
 (9006, np.float64(0.20100756305184245)),
 (3709, np.float64(0.20032733246124987)),
 (2963, np.float64(0.19512313566832118)),
 (884, np.float64(0.19462473604038075)),
 (1009, np.float64(0.1939524551505708)),
 (7478, np.float64(0.1860968420796942)),
 (2796, np.float64(0.17978662999019787)),
 (9139, np.float64(0.17588161767036214)),
 (725, np.float64(0.17407765595569785)),
 (6156, np.float64(0.17407765595569785)),
 (6758, np.float64(0.17407765595569785)),
 (7324, np.float64(0.17170914210964275)),
 (393, np.float64(0.16943474841747155)),
 (791, np.float64(0.16514456476895412)),
 (2605, np.float64(0.16514456476895412)),
 (4068, np.float64(0.16514456476895412)),
 (4811, np.float64(0.16514456476895412)),
 (9520, np.float64(0.16412198797244368)),
 (2927, np.float64(0.16299398843414567)),
 (7271, np.float64(0.15974461276617435)),
 (1175, np.float64(0.1592795619605697)),
 (1264, np.float64(0.1592795619605697)),
 (715, np.float64(0.15927956196056967)),
 (5776, np.float64(0.15891043154093204)),
 (2120, np.float64(0.1574591643244434)),
 (4491, np.float64(0.1574591643244434)),
 (5587, np.float64(0.15569978883230462)),
 (4155, np.float64(0.15386436372416593)),
 (4201, np.float64(0.15386436372416593)),
 (4086, np.float64(0.1519474352795173)),
 (279, np.float64(0.15151515151515155)),
 (8671, np.float64(0.14920941939059815)),
 (4078, np.float64(0.1484539238050411)),
 (7828, np.float64(0.1484539238050411)),
 (9718, np.float64(0.1484539238050411)),
 (5428, np.float64(0.14712247158412492)),
 (4064, np.float64(0.14669540980778403)),
 (4295, np.float64(0.14519080172812557)),
 (196, np.float64(0.14506471329641488)),
 (5508, np.float64(0.14506471329641488)),
 (1407, np.float64(0.1448413648755803)),
 (4347, np.float64(0.1448413648755803)),
 (8832, np.float64(0.1448413648755803)),
 (9275, np.float64(0.1448413648755803)),
 (6093, np.float64(0.14363791428130826)),
 (4406, np.float64(0.14309095175803563)),
 (9980, np.float64(0.14309095175803563)),
 (608, np.float64(0.14213381090374033)),
 (7771, np.float64(0.1411956236812263)),
 (729, np.float64(0.13957263155977065)),
 (4063, np.float64(0.13957263155977065)),
 (6277, np.float64(0.13957263155977065)),
 (9516, np.float64(0.13957263155977065)),
 (1068, np.float64(0.1392621247645583)),
 (5882, np.float64(0.1392621247645583)),
 (9579, np.float64(0.1392621247645583)),
 (7871, np.float64(0.13762047064079508)),
 (9126, np.float64(0.13762047064079508)),
 (7395, np.float64(0.1365577483997838)),
 (7544, np.float64(0.1365577483997838)),
 (6284, np.float64(0.13593181195675924)),
 (552, np.float64(0.1348399724926484)),
 (2081, np.float64(0.1348399724926484)),
 (2925, np.float64(0.1348399724926484)),
 (4222, np.float64(0.1348399724926484)),
 (6327, np.float64(0.1348399724926484)),
 (7418, np.float64(0.1348399724926484)),
 (7471, np.float64(0.1348399724926484)),
 (7558, np.float64(0.1348399724926484)),
 (8085, np.float64(0.1348399724926484)),
 (8206, np.float64(0.1348399724926484)),
 (8800, np.float64(0.1348399724926484)),
 (9818, np.float64(0.1348399724926484)),
 (663, np.float64(0.1343038273375634)),
 (7677, np.float64(0.1343038273375634)),
 (7878, np.float64(0.13400504203456162)),
 (2225, np.float64(0.1315903389919538)),
 (3159, np.float64(0.1315903389919538)),
 (5182, np.float64(0.1315903389919538)),
 (5860, np.float64(0.1315903389919538)),
 (8911, np.float64(0.1315903389919538)),
 (143, np.float64(0.1305582419667734)),
 (1038, np.float64(0.1305582419667734)),
 (4141, np.float64(0.1305582419667734)),
 (7440, np.float64(0.1305582419667734)),
 (7993, np.float64(0.1305582419667734)),
 (9475, np.float64(0.1305582419667734)),
 (9756, np.float64(0.1305582419667734)),
 (1646, np.float64(0.1297498240269205)),
 (8760, np.float64(0.1297498240269205)),
 (52, np.float64(0.12955005512625917)),
 (2583, np.float64(0.1293016367670472)),
 (4942, np.float64(0.1293016367670472)),
 (645, np.float64(0.12712834523274563)),
 (1507, np.float64(0.12712834523274563)),
 (1544, np.float64(0.12712834523274563)),
 (2009, np.float64(0.12712834523274563)),
 (2529, np.float64(0.12712834523274563)),
 (6254, np.float64(0.12695917902975642)),
 (3250, np.float64(0.12666009927622474)),
 (4378, np.float64(0.12666009927622474)),
 (5700, np.float64(0.12666009927622474)),
 (7884, np.float64(0.12666009927622474)),
 (87, np.float64(0.1250610798961445)),
 (6162, np.float64(0.1250610798961445)),
 (6892, np.float64(0.1250610798961445)),
 (8263, np.float64(0.1250610798961445)),
 (8540, np.float64(0.1250610798961445)),
 (1489, np.float64(0.12309149097933275)),
 (1619, np.float64(0.12309149097933275)),
 (2084, np.float64(0.12309149097933275)),
 (3182, np.float64(0.12309149097933275)),
 (5843, np.float64(0.12309149097933275)),
 (6297, np.float64(0.12309149097933275)),
 (7809, np.float64(0.12309149097933275)),
 (441, np.float64(0.12309149097933274)),
 (2626, np.float64(0.12309149097933274)),
 (4271, np.float64(0.12309149097933274)),
 (4330, np.float64(0.12309149097933274)),
 (5027, np.float64(0.12309149097933274)),
 (7325, np.float64(0.12309149097933274)),
 (9113, np.float64(0.12309149097933274)),
 (3906, np.float64(0.12187873735452177)),
 (6538, np.float64(0.12121212121212123)),
 (7153, np.float64(0.12121212121212123)),
 (7921, np.float64(0.12121212121212123)),
 (8538, np.float64(0.12121212121212123)),
 (1449, np.float64(0.11980845957463077)),
 (1881, np.float64(0.11980845957463077)),
 (3833, np.float64(0.11980845957463077)),
 (3884, np.float64(0.11980845957463077)),
 (8128, np.float64(0.11980845957463077)),
 (9669, np.float64(0.11980845957463077)),
 (5541, np.float64(0.11941628680530642)),
 (2945, np.float64(0.1185477931931699)),
 (1918, np.float64(0.11769797726729994)),
 (4273, np.float64(0.11769797726729994)),
 (8640, np.float64(0.11736313170325507)),
 (1970, np.float64(0.11677484162422844)),
 (2426, np.float64(0.11677484162422844)),
 (1533, np.float64(0.1160517706371319)),
 (5193, np.float64(0.1160517706371319)),
 (5224, np.float64(0.1160517706371319)),
 (5557, np.float64(0.1160517706371319)),
 (5983, np.float64(0.1160517706371319)),
 (6561, np.float64(0.1160517706371319)),
 (6990, np.float64(0.1160517706371319)),
 (8914, np.float64(0.1160517706371319)),
 (278, np.float64(0.11396057645963797)),
 (1039, np.float64(0.11396057645963797)),
 (1105, np.float64(0.11396057645963797)),
 (1480, np.float64(0.11396057645963797)),
 (1775, np.float64(0.11396057645963797)),
 (2112, np.float64(0.11396057645963797)),
 (4023, np.float64(0.11396057645963797)),
 (5456, np.float64(0.11396057645963797)),
 (6294, np.float64(0.11396057645963797)),
 (6402, np.float64(0.11396057645963797)),
 (7599, np.float64(0.11396057645963797)),
 (2352, np.float64(0.11331490227483418)),
 (1754, np.float64(0.11295649894498103)),
 (6418, np.float64(0.11295649894498103)),
 (4485, np.float64(0.11236664374387367)),
 (6862, np.float64(0.11149893466761211)),
 (8249, np.float64(0.11149893466761211)),
 (933, np.float64(0.11134044285378084)),
 (1657, np.float64(0.11134044285378084)),
 (2148, np.float64(0.11134044285378084)),
 (4608, np.float64(0.11134044285378084)),
 (6232, np.float64(0.11053942207134548)),
 (295, np.float64(0.11009637651263607)),
 (766, np.float64(0.11009637651263607)),
 (2568, np.float64(0.11009637651263607)),
 (2766, np.float64(0.11009637651263607)),
 (3848, np.float64(0.11009637651263607)),
 (4988, np.float64(0.11009637651263607)),
 (5558, np.float64(0.11009637651263607)),
 (5676, np.float64(0.11009637651263607)),
 (6965, np.float64(0.11009637651263607)),
 (7049, np.float64(0.11009637651263607)),
 (1191, np.float64(0.10889310129609417)),
 (8030, np.float64(0.10889310129609417)),
 (8071, np.float64(0.10889310129609417)),
 (9804, np.float64(0.10889310129609417)),
 (3269, np.float64(0.10874544956540738)),
 (5985, np.float64(0.10874544956540738)),
 (7853, np.float64(0.10874544956540738)),
 (834, np.float64(0.10744306187005072)),
 (6850, np.float64(0.10744306187005072)),
 (825, np.float64(0.10660035817780525)),
 (1853, np.float64(0.10660035817780525)),
 (3458, np.float64(0.10660035817780525)),
 (4534, np.float64(0.10660035817780525)),
 (9173, np.float64(0.10660035817780525)),
 (9745, np.float64(0.10618637464037979)),
 (3762, np.float64(0.10555008273018726)),
 (2758, np.float64(0.10497277621629561)),
 (2980, np.float64(0.10497277621629561)),
 (3041, np.float64(0.10497277621629561)),
 (3690, np.float64(0.10497277621629561)),
 (3893, np.float64(0.10497277621629561)),
 (4987, np.float64(0.10497277621629561)),
 (5168, np.float64(0.10497277621629561)),
 (5176, np.float64(0.10497277621629561)),
 (5512, np.float64(0.10497277621629561)),
 (8283, np.float64(0.10497277621629561)),
 (8410, np.float64(0.10497277621629561)),
 (9493, np.float64(0.10497277621629561)),
 (6963, np.float64(0.10478243557698859)),
 (3881, np.float64(0.10444659357341872)),
 (3883, np.float64(0.10444659357341872)),
 (5551, np.float64(0.10444659357341872)),
 (6074, np.float64(0.10444659357341872)),
 (8897, np.float64(0.10444659357341872)),
 (2028, np.float64(0.10403129732205987)),
 (4905, np.float64(0.10379985922153641)),
 (5876, np.float64(0.10379985922153641)),
 (4953, np.float64(0.10241831129983785)),
 (6329, np.float64(0.10241831129983785)),
 (8908, np.float64(0.10241831129983785)),
 (4071, np.float64(0.10156734322380513)),
 (8755, np.float64(0.10156734322380513)),
 (8841, np.float64(0.10156734322380513)),
 (190, np.float64(0.10050378152592122)),
 (331, np.float64(0.10050378152592122)),
 (501, np.float64(0.10050378152592122)),
 (531, np.float64(0.10050378152592122)),
 (989, np.float64(0.10050378152592122)),
 (1223, np.float64(0.10050378152592122)),
 (1516, np.float64(0.10050378152592122)),
 (1996, np.float64(0.10050378152592122)),
 (2233, np.float64(0.10050378152592122)),
 (2294, np.float64(0.10050378152592122)),
 (2325, np.float64(0.10050378152592122)),
 (2334, np.float64(0.10050378152592122)),
 (2353, np.float64(0.10050378152592122)),
 (2813, np.float64(0.10050378152592122)),
 (3148, np.float64(0.10050378152592122)),
 (4124, np.float64(0.10050378152592122)),
 (4160, np.float64(0.10050378152592122)),
 (4296, np.float64(0.10050378152592122)),
 (5015, np.float64(0.10050378152592122)),
 (5262, np.float64(0.10050378152592122)),
 (6563, np.float64(0.10050378152592122)),
 (6756, np.float64(0.10050378152592122)),
 (7641, np.float64(0.10050378152592122)),
 (8043, np.float64(0.10050378152592122)),
 (8374, np.float64(0.10050378152592122)),
 (8514, np.float64(0.10050378152592122)),
 (8537, np.float64(0.10050378152592122)),
 (8687, np.float64(0.10050378152592122)),
 (8751, np.float64(0.10050378152592122)),
 (8929, np.float64(0.10050378152592122)),
 (9646, np.float64(0.10050378152592122)),
 (9766, np.float64(0.10050378152592122)),
 (9990, np.float64(0.10050378152592122)),
 (2011, np.float64(0.10050378152592121)),
 (2405, np.float64(0.10050378152592121)),
 (2712, np.float64(0.10050378152592121)),
 (3130, np.float64(0.10050378152592121)),
 (3268, np.float64(0.10050378152592121)),
 (4241, np.float64(0.10050378152592121)),
 (4563, np.float64(0.10050378152592121)),
 (4632, np.float64(0.10050378152592121)),
 (6607, np.float64(0.10050378152592121)),
 (7055, np.float64(0.10050378152592121)),
 (6799, np.float64(0.09947294626039876)),
 (6881, np.float64(0.09947294626039876)),
 (208, np.float64(0.09869275424396534)),
 (1599, np.float64(0.09869275424396534)),
 (1787, np.float64(0.09869275424396534)),
 (2070, np.float64(0.09869275424396534)),
 (2936, np.float64(0.09869275424396534)),
 (3841, np.float64(0.09869275424396534)),
 (6527, np.float64(0.09869275424396534)),
 (6904, np.float64(0.09869275424396534)),
 (7756, np.float64(0.09869275424396534)),
 (8646, np.float64(0.09869275424396534)),
 (9331, np.float64(0.09869275424396534)),
 (3075, np.float64(0.0984731927834662)),
 (7350, np.float64(0.0984731927834662)),
 (168, np.float64(0.0969762275752854)),
 (477, np.float64(0.0969762275752854)),
 (878, np.float64(0.0969762275752854)),
 (2300, np.float64(0.0969762275752854)),
 (2656, np.float64(0.0969762275752854)),
 (3042, np.float64(0.0969762275752854)),
 (7003, np.float64(0.0969762275752854)),
 (7166, np.float64(0.0969762275752854)),
 (408, np.float64(0.09656090991705353)),
 (655, np.float64(0.09656090991705353)),
 (773, np.float64(0.09656090991705353)),
 (2274, np.float64(0.09656090991705353)),
 (3292, np.float64(0.09656090991705353)),
 (3349, np.float64(0.09656090991705353)),
 (3517, np.float64(0.09656090991705353)),
 (3587, np.float64(0.09656090991705353)),
 (3645, np.float64(0.09656090991705353)),
 (4006, np.float64(0.09656090991705353)),
 (4388, np.float64(0.09656090991705353)),
 (4403, np.float64(0.09656090991705353)),
 (4864, np.float64(0.09656090991705353)),
 (5342, np.float64(0.09656090991705353)),
 (6683, np.float64(0.09656090991705353)),
 (6746, np.float64(0.09656090991705353)),
 (6980, np.float64(0.09656090991705353)),
 (7493, np.float64(0.09656090991705353)),
 (8086, np.float64(0.09656090991705353)),
 (8530, np.float64(0.09656090991705353)),
 (8637, np.float64(0.09656090991705353)),
 (7138, np.float64(0.09615088296963142)),
 (6664, np.float64(0.09564561997176209)),
 (8989, np.float64(0.09553752543358544)),
 (790, np.float64(0.09534625892455922)),
 (1193, np.float64(0.09534625892455922)),
 (6802, np.float64(0.09534625892455922)),
 (7533, np.float64(0.09534625892455922)),
 (8799, np.float64(0.09534625892455922)),
 (4077, np.float64(0.09475587393582686)),
 (2560, np.float64(0.09379580992210838)),
 (5503, np.float64(0.09379580992210838)),
 (5603, np.float64(0.09379580992210838)),
 (7156, np.float64(0.09379580992210838)),
 (9428, np.float64(0.09379580992210838)),
 (617, np.float64(0.09379580992210837)),
 (71, np.float64(0.0930484210398471)),
 (384, np.float64(0.0930484210398471)),
 (554, np.float64(0.0930484210398471)),
 (625, np.float64(0.0930484210398471)),
 (955, np.float64(0.0930484210398471)),
 (1390, np.float64(0.0930484210398471)),
 (1573, np.float64(0.0930484210398471)),
 (2136, np.float64(0.0930484210398471)),
 (2335, np.float64(0.0930484210398471)),
 (2456, np.float64(0.0930484210398471)),
 (2659, np.float64(0.0930484210398471)),
 (2895, np.float64(0.0930484210398471)),
 (2932, np.float64(0.0930484210398471)),
 (3117, np.float64(0.0930484210398471)),
 (4652, np.float64(0.0930484210398471)),
 (4711, np.float64(0.0930484210398471)),
 (4958, np.float64(0.0930484210398471)),
 (5099, np.float64(0.0930484210398471)),
 (5290, np.float64(0.0930484210398471)),
 (5438, np.float64(0.0930484210398471)),
 (6459, np.float64(0.0930484210398471)),
 (6723, np.float64(0.0930484210398471)),
 (6967, np.float64(0.0930484210398471)),
 (7207, np.float64(0.0930484210398471)),
 (7392, np.float64(0.0930484210398471)),
 (7984, np.float64(0.0930484210398471)),
 (8346, np.float64(0.0930484210398471)),
 (8424, np.float64(0.0930484210398471)),
 (8493, np.float64(0.0930484210398471)),
 (8842, np.float64(0.0930484210398471)),
 (140, np.float64(0.09231861823449955)),
 (2695, np.float64(0.09231861823449955)),
 (3508, np.float64(0.09231861823449955)),
 (3617, np.float64(0.09231861823449955)),
 (4234, np.float64(0.09231861823449955)),
 (5377, np.float64(0.09231861823449955)),
 (6835, np.float64(0.09231861823449955)),
 (8170, np.float64(0.09231861823449955)),
 (8950, np.float64(0.09231861823449955)),
 (1570, np.float64(0.09226097313475812)),
 (9363, np.float64(0.09143006417649888)),
 (1537, np.float64(0.09090909090909093)),
 (2498, np.float64(0.09090909090909093)),
 (5119, np.float64(0.09090909090909093)),
 (5774, np.float64(0.09090909090909093)),
 (6243, np.float64(0.09090909090909093)),
 (7060, np.float64(0.09090909090909093)),
 (7362, np.float64(0.09090909090909093)),
 (5639, np.float64(0.09090909090909091)),
 (8108, np.float64(0.09065192181986734)),
 (5795, np.float64(0.0902550601789804)),
 (133, np.float64(0.08989331499509894)),
 (987, np.float64(0.08989331499509894)),
 (1145, np.float64(0.08989331499509894)),
 (1284, np.float64(0.08989331499509894)),
 (1561, np.float64(0.08989331499509894)),
 (2219, np.float64(0.08989331499509894)),
 (2330, np.float64(0.08989331499509894)),
 (2500, np.float64(0.08989331499509894)),
 (3026, np.float64(0.08989331499509894)),
 (3242, np.float64(0.08989331499509894)),
 (3347, np.float64(0.08989331499509894)),
 (3359, np.float64(0.08989331499509894)),
 (4247, np.float64(0.08989331499509894)),
 (4302, np.float64(0.08989331499509894)),
 (4508, np.float64(0.08989331499509894)),
 (5394, np.float64(0.08989331499509894)),
 (5413, np.float64(0.08989331499509894)),
 (5434, np.float64(0.08989331499509894)),
 (5443, np.float64(0.08989331499509894)),
 (5729, np.float64(0.08989331499509894)),
 (5745, np.float64(0.08989331499509894)),
 (5782, np.float64(0.08989331499509894)),
 (6153, np.float64(0.08989331499509894)),
 (6458, np.float64(0.08989331499509894)),
 (7135, np.float64(0.08989331499509894)),
 (7255, np.float64(0.08989331499509894)),
 (7519, np.float64(0.08989331499509894)),
 (7531, np.float64(0.08989331499509894)),
 (8115, np.float64(0.08989331499509894)),
 (8266, np.float64(0.08989331499509894)),
 (8274, np.float64(0.08989331499509894)),
 (8503, np.float64(0.08989331499509894)),
 (8632, np.float64(0.08989331499509894)),
 (8773, np.float64(0.08989331499509894)),
 (8884, np.float64(0.08989331499509894)),
 (8922, np.float64(0.08989331499509894)),
 (9222, np.float64(0.08989331499509894)),
 (9587, np.float64(0.08989331499509894)),
 (9770, np.float64(0.08989331499509894)),
 (747, np.float64(0.08956221510397981)),
 (1028, np.float64(0.08956221510397981)),
 (1792, np.float64(0.08956221510397981)),
 (3050, np.float64(0.08956221510397981)),
 (3789, np.float64(0.08956221510397981)),
 (6017, np.float64(0.08956221510397981)),
 (7429, np.float64(0.08956221510397981)),
 (7505, np.float64(0.08956221510397981)),
 (8433, np.float64(0.08956221510397981)),
 (8825, np.float64(0.08956221510397981)),
 (2001, np.float64(0.08883363181483771)),
 (6923, np.float64(0.08843153765707638)),
 (313, np.float64(0.08827348295047496)),
 (354, np.float64(0.08827348295047496)),
 (1813, np.float64(0.08827348295047496)),
 (2654, np.float64(0.08827348295047496)),
 (3930, np.float64(0.08827348295047496)),
 (4080, np.float64(0.08827348295047496)),
 (5294, np.float64(0.08827348295047496)),
 (6532, np.float64(0.08827348295047496)),
 (9226, np.float64(0.08827348295047496)),
 (8519, np.float64(0.08772689266130253)),
 (138, np.float64(0.08703882797784893)),
 (520, np.float64(0.08703882797784893)),
 (551, np.float64(0.08703882797784893)),
 (652, np.float64(0.08703882797784893)),
 (653, np.float64(0.08703882797784893)),
 (919, np.float64(0.08703882797784893)),
 (1120, np.float64(0.08703882797784893)),
 (1462, np.float64(0.08703882797784893)),
 (1583, np.float64(0.08703882797784893)),
 (1795, np.float64(0.08703882797784893)),
 (1976, np.float64(0.08703882797784893)),
 (2829, np.float64(0.08703882797784893)),
 (2862, np.float64(0.08703882797784893)),
 (2966, np.float64(0.08703882797784893)),
 (3104, np.float64(0.08703882797784893)),
 (3164, np.float64(0.08703882797784893)),
 (3786, np.float64(0.08703882797784893)),
 (4377, np.float64(0.08703882797784893)),
 (4421, np.float64(0.08703882797784893)),
 (4843, np.float64(0.08703882797784893)),
 (5089, np.float64(0.08703882797784893)),
 (5130, np.float64(0.08703882797784893)),
 (5867, np.float64(0.08703882797784893)),
 (6087, np.float64(0.08703882797784893)),
 (6308, np.float64(0.08703882797784893)),
 (6539, np.float64(0.08703882797784893)),
 (6662, np.float64(0.08703882797784893)),
 (6753, np.float64(0.08703882797784893)),
 (6822, np.float64(0.08703882797784893)),
 (7318, np.float64(0.08703882797784893)),
 (7336, np.float64(0.08703882797784893)),
 (8222, np.float64(0.08703882797784893)),
 (8439, np.float64(0.08703882797784893)),
 (8638, np.float64(0.08703882797784893)),
 (8917, np.float64(0.08703882797784893)),
 (9316, np.float64(0.08703882797784893)),
 (9494, np.float64(0.08703882797784893)),

In [33]:
for i in dist[0:5]:
  print(new_df.loc[i[0], 'title'])

The Shawshank Redemption
The Woodsman
Escape Plan
Sherlock Jr.
Cool Hand Luke

In [35]:
from scipy.spatial import distance
def recommend(movies):
  index = new_df[new_df['title'] == movies].index[0]
  distancest = sorted(list(enumerate(sin[index])), reverse=True, key=lambda vector:vector[1])
  for i in distancest[0:5]:
    print(new_df.loc[i[0], 'title'])

In [36]:
recommend('Gandhi')

Gandhi
A Passage to India
Female Agents
Rang De Basanti
For Your Eyes Only